In [17]:
import numpy as np
import math

In [19]:
a = np.array([1,2,3])
print(a)
print(a.ndim)

[1 2 3]
1


In [25]:
c = np.array([2.2, 5, 1.3])
c.dtype.name

'float64'

In [24]:
b = np.array([[1,2,3], [4,5,6]])
b

b.shape

a.dtype

dtype('int64')

In [28]:
d = np.zeros((2,3))
e = np.ones((2,3))

print(e,d)

[[1. 1. 1.]
 [1. 1. 1.]] [[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
np.random.rand(2,3)


array([[0.92873646, 0.05374792, 0.46940716],
       [0.26287645, 0.73758048, 0.26329286]])

In [32]:
f = np.arange(10, 50,2)
f


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [36]:
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

# Array Operation

In [39]:
a = np.array([10,20,30,40])
b =np.array([1,2,3,4])

c = a - b 
print(c)

d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [45]:
farencheit = np.array([0,-10,-5,-15,0])
celcius = (farencheit - 31) * (5/9)

print(celcius)

[-17.22222222 -22.77777778 -20.         -25.55555556 -17.22222222]


In [48]:
celcius >= -20

celcius % 2 == 0

array([False, False,  True, False, False])

In [52]:
A = np.array([[1,1], [1,0]])
B = np.array([[2,0],[3,4]])

print(A)
print(B)


print(A*B) #element wise product
print(A@B) #matrix product


[[1 1]
 [1 0]]
[[2 0]
 [3 4]]
[[2 0]
 [3 0]]
[[5 4]
 [2 0]]


In [54]:
A.shape
B.shape


(2, 2)

In [60]:
array1 = np.array([[1,3,4], [4,5,6]])
print(array1.dtype)

array2 = np.array([[7.1, 8.2, 9.1], [10.4,11.2, 12.3]])
print(array2.dtype)

int64
float64


In [75]:
a1 = np.random.rand(4)
a2 = np.random.rand(4,1)
a3 = np.array([[1,2,3,4]])
a4 = np.arange(1,4,1)
a5 = np.linspace(1,4,4)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

a1.shape


[0.80035132 0.45845623 0.20168657 0.17643683]
[[0.06411587]
 [0.98309424]
 [0.64734873]
 [0.76761916]]
[[1 2 3 4]]
[1 2 3]
[1. 2. 3. 4.]


(4,)

In [78]:
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
print(result)

['A', 'AA', 'AA', 'AA', 'A']
